namespace CreateStatelEvents
{
    partial class SelectPlayfield
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.PFBox = new System.Windows.Forms.ListBox();
            this.button1 = new System.Windows.Forms.Button();
            this.button2 = new System.Windows.Forms.Button();
            this.SuspendLayout();
            // 
            // PFBox
            // 
            this.PFBox.FormattingEnabled = true;
            this.PFBox.Items.AddRange(new object[] {
            "100 Needed PF-stuff",
            "101 Default Door Links",
            "102 Monster and NPC dependencies",
            "103 Shop and Item Dependencies",
            "104 One Template PF",
            "105 Morten gfx fixes",
            "107 AI graphics dependency",
            "109 LE dependencies",
            "110 Dependency EP1 Mons",
            "111 RK Quick Export Dependancy",
            "120 Camelot",
            "124 Tir Assembly Hall",
            "125 Smuggler\'s Rearranged",
            "127 Condemned Subway (dng)",
            "128 Subway Junction (dng)",
            "152 TheGrid2(dng)",
            "320 AutocontentMidtech(dung)",
            "321 AutocontentHITech(dung)",
            "322 Autocontentdungcave(dung)",
            "324 AutocontentClan(dung)",
            "331 ACD tarm (dng)",
            "341 ACD Grey Caves-Mines dng",
            "346 ACD Omnilab (dng)",
            "351 ACD Subway - Ventil (dng)",
            "362 SL ACG(dng)",
            "382 Alien ACG (dng)",
            "386 Alien Mothership (dng)",
            "500 Parnassos",
            "501 Parnassos Island of Ceremony",
            "505 Avalon",
            "540 Old Athen",
            "545 West Athens",
            "550 Athen Shire",
            "551 Wailing Wastes",
            "556 Coast of Peace",
            "560 Mort",
            "565 Newland Desert",
            "566 Newland City",
            "567 Newland",
            "570 The Perpetual Wastelands",
            "585 Aegean",
            "586 Wartorn Valley",
            "590 Central Artery Valley",
            "595 Deep Artery Valley",
            "600 Varmint Woods",
            "605 Belial Forest",
            "610 Southern Artery Valley",
            "615 Southern Fouls Hills",
            "620 Eastern Fouls Plains",
            "625 Milky Way",
            "630 Pleasant Meadows",
            "635 Stret East Bank GOLD",
            "640 Tir",
            "641 Tir Arena",
            "646 Tir County",
            "647 Greater Tir County",
            "650 Upper Stret East Bank",
            "655 Andromeda",
            "656 Coast of Tranquility",
            "665 Broken Shores",
            "670 Clondyke",
            "685 Galway County",
            "687 Galway Shire",
            "695 Lush Fields",
            "696 Mutant Domain",
            "700 Omni1-HEADQUARTER",
            "705 Omni1 Entertainment",
            "706 Omni Entertainment Arena",
            "710 Omni-1 Trade",
            "716 Omni Forest",
            "717 Greater Omni Forest",
            "730 Rome Park",
            "735 Rome Blue",
            "740 Rome Green",
            "750 The Reck",
            "760 4 Holes",
            "790 Stret West Bank",
            "791 Holes in the Wall",
            "795 The Longest Road",
            "800 Borealis",
            "896 Character Creation Lab Dng",
            "950 Omni Training",
            "952 Clan Training",
            "953 Clan Backyard",
            "954 Neutral Training",
            "955 Neutral Backyard",
            "1001 Senitel rec_centre (wine) GOLD",
            "1002 medical/eating (wine) GOLD",
            "1003 Wine hq (wine) GOLD",
            "1004 barracks (wine) GOLD",
            "1005 storage (wine) GOLD",
            "1011 2HO HQ (streteast) GOLD",
            "1012 2HO satellite (streteast) GOLD",
            "1021 OMni barracks (USEB) GOLD",
            "1031 Avalon omni barracks",
            "1136 Mir shop clan",
            "1137 mir shop omni",
            "1180 ord_smarket_clan_basic",
            "1181 ord_smarket_clan_advanced",
            "1182 ord_smarket_clan_sup",
            "1183 ord_smarket_omni_basic",
            "1184 ord_smarket_omni_advanced",
            "1185 ord_smarket_omni_sup",
            "1186 ord_smarket_neut_basic",
            "1187 ord_smarket_neut_advanced",
            "1189 spec_smarket_clan_advanced",
            "1190 spec_smarket_clan_sup",
            "1191 spec_smarket_omni_advanced",
            "1192 spec_smarket_omni_sup",
            "1193 spec_smarket_neut_basic",
            "1211 basicomniapartment dng",
            "1231 Clan Small Clan Apartment",
            "1232 Clan Medium Clan Apartment",
            "1233 Clan Big Clan Apartment",
            "1241 Neutral Small Clan Apartment",
            "1242 Neutral Medium Clan Apartment",
            "1243 Neutral Big Clan Apartment",
            "1251 Omni Small Guild",
            "1321 tir clanbuilding2 dng",
            "1322 tir clanbuilding1 dng",
            "1323 tir clanbuilding9 dng",
            "1324 tir clanbuilding11 dng",
            "1325 tir clanbuilding12 dng",
            "1326 tir clanbuilding3",
            "1327 tir clanbuilding_pod4 dng",
            "1328 tir clanbuilding5 dng",
            "1329 tir clanbuilding6 dng",
            "1330 tir clanbuilding7 dng",
            "1404 The Temple of Home",
            "1405 clanapartment",
            "1406 omniapartment",
            "1407 neutralapartment",
            "1410 items",
            "1421 avalon_building3 dng",
            "1422 avalon_building4 dng",
            "1423 avalon_building5",
            "1426 Clan Registration dng",
            "1427 Omni registration dng",
            "1428 Neutral organisation dng",
            "1501 omnimine_hq_building_06",
            "1502 omnimine_hq_building_02",
            "1503 omnimine_hq_building_04",
            "1504 omnimine_hq_building_07",
            "1505 omnimine_hq_building_08",
            "1506 omnimine_hq_building_09",
            "1507 omnimine_hq_building10",
            "1510 Neutral Insurance building",
            "1511 Neutral Mission building",
            "1601 athens_clanhouse1 VP dng",
            "1602 athens_clanhouse3 VP dng",
            "1603 athens_clanhouse4 VP dng",
            "1604 athens_clanhouse12 VP dng",
            "1611 Swamp_house01 VP dng",
            "1612 Swamp_house02",
            "1613 swamp_house03 VP dng",
            "1614 Swamp_house04 VP dng",
            "1621 wood_shack_01 VP dng",
            "1622 wood_shack_02 VP dng",
            "1623 wood_shack_03 VP dng",
            "1624 wood_shack_04 VP dng",
            "1625 wood_shack_05 VP dng",
            "1626 wood_shack_06 VP dng",
            "1627 wood_shack_07 VP dng",
            "1641 lowtech_building1 VP dng",
            "1642 lowtech_building2 VP dng",
            "1643 lowtech_building3 VP dng",
            "1644 lowtech_building4 VP dng",
            "1645 lowtech_building5 VP dng",
            "1646 lowtech_building6 VP dng",
            "1647 lowtech_building7 VP dng",
            "1648 lowtech_waterwell VP dng",
            "1651 rome_shopbuilding1 VP dng",
            "1652 rome_simplebuilding VP dng",
            "1653 rome_simplebuilding1 VP dng",
            "1661 rhino_house1 VP dng",
            "1662 rhino_house2 VP dng",
            "1663 rhino_house3 VP dng",
            "1671 reck_trading_outpost_bunker1 VP",
            "1672 reck_trading_outpost_bunker2 VP",
            "1674 reck_trading_outpost_bunker4 VP",
            "1675 reck_trading_outpost_bunker5 VP",
            "1701 Home VP dng 1 medium",
            "1702 Home VP dng 2 big",
            "1703 Home VP dng 3 small",
            "1711 Factory VP dng barracks",
            "1712 Factory VP dng factory",
            "1721 LD VP dng 1",
            "1722 LD VP dng 2",
            "1741 enigma_tree01",
            "1742 enigma_tree02",
            "1743 enigma_tree03",
            "1826 Dancing Atrox Bar",
            "1827 Omni Military Barracks",
            "1833 Dng: Cyborg Barracks",
            "1836 Baboons Nightclub",
            "1840 Rompa Bar",
            "1846 McRiid\'s Office",
            "1862 The Smugglers Den",
            "1866 The HQ of Omni-Mine",
            "1886 Versailles Tower",
            "1887 Treepine Hut",
            "1891 The Happy Rebel Inn",
            "1892 Enjoy it While it Lasts",
            "1893 The Cup",
            "1894 Clan Registration Office",
            "1901 Neutral Organisation Office",
            "1902 Neuters \'R\' Us",
            "1913 Reet Retreat (dng)",
            "1931 Dng: Temple of Three Winds",
            "1933 Dng: Steps of Madness",
            "1941 Bio MARE",
            "1943 Dng: High Level ToTW",
            "2001 clan_basic_weapons_shop",
            "2002 clan_basic_armor_shop",
            "2003 clan_basic_pharmasist_shop",
            "2004 clan_basic_clothes_shop",
            "2005 clan_basic_implants_shop",
            "2010 clan_advanced_weapons_shop",
            "2011 clan_advanced_armor_shop",
            "2012 clan_advanced_pharmacist_shop",
            "2013 clan_advanced_implants_shop",
            "2020 clan_sup_weapons_shop",
            "2021 clan_sup_armor_shop",
            "2022 clan_sup_pharmacist_shop",
            "2023 clan_sup_implants_shop",
            "2030 omni_basic_weapons_shop",
            "2031 omni_basic_armor_shop",
            "2032 omni_basic_pharmacist",
            "2033 omni_basic_clothes_shop",
            "2034 omni_basic_implants_shop",
            "2040 omni_advanced_weapons_shop",
            "2041 omni_advanced_armor_shop",
            "2042 omni_advanced_pharmacist_shop",
            "2043 omni_advanced_implants_shop",
            "2050 omni_sup_weapons_shop",
            "2051 omni_sup_armor_shop",
            "2052 omni_sup_pharmacist_shop",
            "2053 omni_sup_implants_shop",
            "2060 neut_basic_weapon _shop",
            "2061 neut_basic_armor_shop",
            "2062 neut_basic_pharmacist_shop",
            "2063 neut_basic_clothes_shop",
            "2064 neut_basic_implants_shop",
            "2070 neut_advanced_weapons_shop",
            "2071 neut_advanced_armor_shop",
            "2072 neut_advanced_pharmacist_shop",
            "2073 neut_advanced_implants_shop",
            "2096 4holes Fashion",
            "3000 Omni-1 Entertainment Backyard 1",
            "3001 Omni-1 Entertainment Backyard 2",
            "3002 Omni-1 Entertainment Backyard 3",
            "3003 Omni-1 Entertainment Backyard 4",
            "3004 Omni-1 Entertainment Backyard 5",
            "3005 Omni-1 Entertainment Backyard 6",
            "3006 Omni-1 Entertainment Backyard 7",
            "3007 Omni-1 Entertainment Backyard 8",
            "3008 Omni-1 Entertainment Backyard 9",
            "3009 Omni-1 Entertainment Backyard 10",
            "3010 Omni-1 Entertainment Backyard 11",
            "3011 Omni-1 Entertainment Backyard 12",
            "3012 Omni-1 Entertainment Backyard 13",
            "3013 Omni-1 Entertainment Backyard 14",
            "3014 Omni-1 Entertainment Backyard 15",
            "3015 Omni-1 Entertainment Backyard 16",
            "3016 Omni-1 Entertainment Backyard 17",
            "3017 Omni-1 Entertainment Backyard 18",
            "3018 Omni-1 Entertainment Backyard 19",
            "3019 Omni-1 Entertainment Backyard 20",
            "3020 Omni-1 Trade Backyard 1",
            "3021 Omni-1 Trade Backyard 2",
            "3022 Omni-1 Trade Backyard 3",
            "3023 Omni-1 Trade Backyard 4",
            "3024 Omni-1 Trade Backyard 5",
            "3025 Omni-1 Trade Backyard 6",
            "3026 Omni-1 Trade Backyard 7",
            "3027 Omni-1 Trade Backyard 8",
            "3028 Omni-1 Trade Backyard 9",
            "3029 Omni-1 Trade Backyard 10",
            "3030 Omni-1 Trade Backyard 11",
            "3031 Omni-1 Trade Backyard 12",
            "3032 Omni-1 Trade Backyard 13",
            "3033 Omni-1 Trade Backyard 14",
            "3034 Omni-1 Trade Backyard 15",
            "3035 Omni-1 Trade Backyard 16",
            "3036 Omni-1 Trade Backyard 17",
            "3037 Omni-1 Trade Backyard 18",
            "3038 Omni-1 Trade Backyard 19",
            "3039 Omni-1 Trade Backyard 20",
            "3040 Rome Blue Backyard 1",
            "3041 Rome Blue Backyard 2",
            "3042 Rome Blue Backyard 3",
            "3043 Rome Blue Backyard 4",
            "3044 Rome Blue Backyard 5",
            "3045 Rome Blue Backyard 6",
            "3046 Rome Blue Backyard 7",
            "3047 Rome Blue Backyard 8",
            "3048 Rome Blue Backyard 9",
            "3049 Rome Blue Backyard 10",
            "3050 Rome Green Backyard 1",
            "3051 Rome Green Backyard 2",
            "3052 Rome Green Backyard 3",
            "3053 Rome Green Backyard 4",
            "3054 Rome Green Backyard 5",
            "3055 Rome Green Backyard 6",
            "3056 Rome Green Backyard 7",
            "3057 Rome Green Backyard 8",
            "3058 Rome Green Backyard 9",
            "3059 Rome Green Backyard 10",
            "3060 Newland Backyard 1",
            "3061 Newland Backyard 2",
            "3062 Newland Backyard 3",
            "3063 Newland Backyard 4",
            "3064 Newland Backyard 5",
            "3065 Newland Backyard 6",
            "3066 Newland Backyard 7",
            "3067 Newland Backyard 8",
            "3068 Newland Backyard 9",
            "3069 Newland Backyard 10",
            "3070 Newland Backyard 11",
            "3071 Newland Backyard 12",
            "3080 Borealis Backyard 1",
            "3081 Borealis Backyard 2",
            "3082 Borealis Backyard 3",
            "3083 Borealis Backyard 4",
            "3084 Borealis Backyard 5",
            "3085 Borealis Backyard 6",
            "3086 Borealis Backyard 7",
            "3087 Borealis Backyard 8",
            "3088 Borealis Backyard 9",
            "3089 Borealis Backyard 10",
            "3100 Tir Backyard 1",
            "3101 Tir Backyard 2",
            "3102 Tir Backyard 3",
            "3103 Tir Backyard 4",
            "3104 Tir Backyard 5",
            "3105 Tir Backyard 6",
            "3106 Tir Backyard 7",
            "3107 Tir Backyard 8",
            "3108 Tir Backyard 9",
            "3109 Tir Backyard 10",
            "3110 Tir Backyard 11",
            "3111 Tir Backyard 12",
            "3112 Tir Backyard 13",
            "3113 Tir Backyard 14",
            "3114 Tir Backyard 15",
            "3115 Tir Backyard 16",
            "3116 Tir Backyard 17",
            "3117 Tir Backyard 18",
            "3120 Old Athen Backyard 1",
            "3121 Old Athen Backyard 2",
            "3122 Old Athen Backyard 3",
            "3123 Old Athen Backyard 4",
            "3124 Old Athen Backyard 5",
            "3125 Old Athen Backyard 6",
            "3126 Old Athen Backyard 7",
            "3127 Old Athen Backyard 8",
            "3128 Old Athen Backyard 9",
            "3129 Old Athen Backyard 10",
            "3130 Old Athen Backyard 11",
            "3131 Old Athen Backyard 12",
            "3132 Old Athen Backyard 13",
            "3133 Old Athen Backyard 14",
            "3134 Old Athen Backyard 15",
            "3135 Old Athen Backyard 16",
            "3136 Old Athen Backyard 17",
            "3137 Old Athen Backyard 18",
            "3138 Old Athen Backyard 19",
            "3139 Old Athen Backyard 20",
            "3140 West Athen Backyard 1",
            "3141 West Athen Backyard 2",
            "3142 West Athen Backyard 3",
            "3143 West Athen Backyard 4",
            "3144 West Athen Backyard 5",
            "3145 West Athen Backyard 6",
            "3146 West Athen Backyard 7",
            "3147 West Athen Backyard 8",
            "3148 West Athen Backyard 9",
            "3149 West Athen Backyard 10",
            "4001 Jobe Research",
            "4003 Burning Marshes",
            "4005 Burning Marshes",
            "4006 Penumbra",
            "4010 Garden of Redeemed Main",
            "4011 Garden_of_unredeemed",
            "4102 Beer And Booze (dng)",
            "4107 Fixer Grid (dng",
            "4121 Will To Fight",
            "4211 Maze_Acheron",
            "4212 Maze_Letha_scheol_red",
            "4213 Maze_Styx_ado_red",
            "4214 Maze_Eridan",
            "4215 Maze_Phlegethas1",
            "4220 Maze_Acheron (Unre)",
            "4221 Maze_Letha_scheol_unre",
            "4222 Maze_Styx_ado_unre",
            "4223 Maze_Eridan (Unre)",
            "4224 Maze_Phlegethas1 (Unre)",
            "4310 Nascense Frontier",
            "4311 Nascense Wilds",
            "4312 Nascense Swamp",
            "4313 Nascense Training Ground",
            "4314 Jobe Harbour Gateway (dng)",
            "4315 Jobe Market Gateway (dng)",
            "4316 Jobe Plaza Gateway (dng)",
            "4318 Nascense Portal",
            "4320 Penumbra Forest",
            "4321 Penumbra Valley",
            "4322 Penumbra Hollows",
            "4324 Penumbra Transit (dng)",
            "4327 Jobe Apartment Normal (dng)",
            "4328 Pandemonium Caina",
            "4329 Pandemonium Antenora",
            "4330 Pandemonium Ptolemea",
            "4331 Pandemonium Judecca",
            "4334 Rubi-Ka Rumble (dng)",
            "4336 Alappaa",
            "4337 Albtraum",
            "4341 Basic Omni org hq",
            "4342 Basic Clan org hq",
            "4343 Basic Neutral org hq",
            "4344 Advanced Omni org hq",
            "4345 Advanced Clan org hq",
            "4346 Advanced Neutral org hq",
            "4347 Superior Omni org hq",
            "4348 Superior Clan org hq",
            "4349 Superior Neutral org hq",
            "4350 ...remember rule no. 1",
            "4351 Swimming Pool",
            "4354 Uncle Bazzits Workshop (Dng)",
            "4355 Basic Player Market (Dng)",
            "4356 Advanced Player Market [dng]",
            "4357 Superior Player Market [dng]",
            "4360 Clinique Plastique",
            "4363 Tir Night Club (dng)",
            "4364 Unicorn Outpost",
            "4365 Sector 13",
            "4366 Sector 28",
            "4367 Sector 35",
            "4368 Unicorn Outpost - Lower level",
            "4370 new alien",
            "4374 Sector 10",
            "4376 ICC Assembly Hall (dng)",
            "4380 Battle Station 20-49",
            "4381 Battle Station 50-74",
            "4382 Battle Station 75-99",
            "4383 Battle Station 100-124",
            "4384 Battle Station 125-149",
            "4385 Battle Station 150-174",
            "4386 Battle Station 175-199",
            "4387 Battle Station 200-209",
            "4388 Battle Station 210-220",
            "4504 West Buggy (DONT DELETE)",
            "4505 South Buggy (DONT DELETE)",
            "4524 Elysium_pre-split",
            "4525 Jobe",
            "4526 Jobe_pre-split",
            "4530 Jobe Platform",
            "4531 Jobe Harbor",
            "4532 Jobe Market",
            "4533 Jobe Plaza",
            "4534 Jobe Apartment",
            "4540 South of Elysium",
            "4541 West of Elysium",
            "4542 Central Elysium",
            "4543 East of Elysium",
            "4544 North of Elysium",
            "4561 Arrival Hall Gateway (dng)",
            "4563 Hardware Dimension - Basic",
            "4564 Hardware Dimension - Advanced",
            "4565 Hardware Dimenion - Superior",
            "4567 Dimensional Shift - Basic",
            "4568 Dimensional Shift - Advanced",
            "4569 Dimensional Shift - Superior",
            "4571 Heavenly Business - Basic",
            "4572 Heavenly Business - Advanced",
            "4573 Heavenly Business - Superior",
            "4575 IPS Interior - Basic",
            "4576 IPS Interior - Advanced",
            "4577 IPS Interior - Superior",
            "4582 ICC Shuttleport",
            "4604 Arrival_hall",
            "4605\" expansion=\"0\" disabled=\"false\" x=\"32560\" xscale=\"0.86614\" z=\"42798\" zscale=" +
                "\"0.97726\">",
            "    <Name>Inferno",
            "4621 Redeemed Temple (Elysium)",
            "4622 Unredeemed Temple (ELysium)",
            "4623 Redeemed Temple (Scheol)",
            "4624 Unredeemed Temple (Scheol)",
            "4625 Redeemed Temple (Adonis)",
            "4626 Unredeemed Temple (Adonis)",
            "4627 Redeemed Temple (Penumbra)",
            "4628 Unredeemed Temple (Penumbra)",
            "4629 Redeemed Temple (Inferno)",
            "4630 Unredeemed Temple (Inferno)",
            "4676 Garden of Redeemed Nascense",
            "4677 Garden_of_unredeemed Nascense",
            "4678 Garden of Redeemed Elysium",
            "4679 Garden of Redeemed Elysium2",
            "4680 Garden_of_unredeemed Elysium",
            "4681 Garden_of_unredeemed Elysium2",
            "4682 Garden of Redeemed Scheol",
            "4683 Garden_of_unredeemed Scheol",
            "4684 Garden of Redeemed Adonis",
            "4685 Garden of Redeemed Adonis2",
            "4686 Garden_of_unredeemed Adonis",
            "4687 Garden_of_unredeemed Adonis2",
            "4688 Garden of Redeemed Penumbra",
            "4689 Garden of Redeemed Penumbra2",
            "4690 Garden_of_unredeemed Penumbra",
            "4691 Garden_of_unredeemed Penumbra2",
            "4692 Garden of Redeemed Inferno",
            "4693 Garden of Redeemed Inferno2",
            "4694 Garden_of_unredeemed Inferno",
            "4695 Garden_of_unredeemed Inferno2",
            "4696 Garden of Redeemed Pandemonium",
            "4697 Garden of unredeemed Pandemonium",
            "4698 Garden of Redeemed Scheol2",
            "4699 Garden_of_unredeemed Scheol2",
            "4704 Booster Shop (dungeon)",
            "4805 The Crypt of Home",
            "4833 Teleport Tower",
            "4872 Adonis City",
            "4873 Adonis Abyss",
            "4877 Adonis Hallway",
            "4880 Upper Scheol",
            "4881 Lower Scheol",
            "4885 Shadow Crypt",
            "4894 Coast of Harmony",
            "4898 Broken Shores AI movie",
            "4899 Broken Shores AI Demo",
            "6003 The Dig Site  ",
            "6011 Arid Rift",
            "6012 Neretva Canyon",
            "6013 Central Gateway",
            "6014 Inside The Ruin",
            "6015 The Elder Hall",
            "6017 Teachers Chamber",
            "6020 Xan Hub Tower Room 1",
            "6021 Xan Tower",
            "6022 Area X",
            "6024 Sealed Antechamber(dng)",
            "6041 Inside The Ruin",
            "6055 Inside The Machine  ",
            "6056 Dust Brigade Research Facility",
            "6057 Dust Brigade Research Facility 2",
            "6060 Profspecroom",
            "6061 Engineers Dugout",
            "4335 Dark Ruins",
            "4389 Caina",
            "4390 Ptolemea",
            "4391 Judecca",
            "4468 Sector 7",
            "6001 Area",
            "6002 Sunrise Station",
            "6007 Unicorn Defence Hub",
            "6010 Serenity Islands",
            "6035 Dark Ruins",
            "6036 Dark Ruins",
            "6050 Serenity Islands",
            "6051 Serenity Islands",
            "6071 The Grind",
            "6101 Three Craters West",
            "6102 Three Craters East",
            "6104 SBC-Xpm Site Alpha-Romeo 29",
            "6111 Area",
            "6112 Area",
            "6113 Area",
            "6115 Area",
            "6121 Area",
            "6123 Area",
            "6125 Area",
            "6127 Area",
            "6129 Area",
            "6131 Area",
            "6133 Sauna",
            "6211 Area",
            "6300 SBC-Xpm Site Alpha-Romeo 29",
            "6301 SBC-Xpm Site Alpha-Romeo 29",
            "6302 SBC-Xpm Site Alpha-Romeo 29",
            "6303 SBC-Xpm Site Alpha-Romeo 29",
            "6304 SBC-Xpm Site Alpha-Romeo 29",
            "6305 SBC-Xpm Site Alpha-Romeo 29",
            "6306 SBC-Xpm Site Alpha-Romeo 29",
            "6550 Uturn Canyon",
            "6551 Uturn Forest",
            "7010 DOJA Research",
            "7011 Omni Tek Agency",
            "7012 Clan Quest HQ",
            "7013 Antiques and more",
            "7015 Area",
            "7051 Area",
            "7054 Area",
            "7092 Area",
            "8002 Phasefront Racetrack",
            "8004 Area",
            "8006 Generetic Corp. Offices"});
            this.PFBox.Location = new System.Drawing.Point(12, 12);
            this.PFBox.Name = "PFBox";
            this.PFBox.Size = new System.Drawing.Size(339, 355);
            this.PFBox.TabIndex = 0;
            // 
            // button1
            // 
            this.button1.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.button1.Location = new System.Drawing.Point(276, 382);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(75, 23);
            this.button1.TabIndex = 1;
            this.button1.Text = "OK";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // button2
            // 
            this.button2.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.button2.Location = new System.Drawing.Point(195, 382);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(75, 23);
            this.button2.TabIndex = 2;
            this.button2.Text = "Cancel";
            this.button2.UseVisualStyleBackColor = true;
            // 
            // SelectPlayfield
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(363, 417);
            this.Controls.Add(this.button2);
            this.Controls.Add(this.button1);
            this.Controls.Add(this.PFBox);
            this.Name = "SelectPlayfield";
            this.Text = "SelectPlayfield";
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.ListBox PFBox;
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.Button button2;
    }
}